/* drills.js — baseball skill drills for every position (Baseball tab → Drills).

   Each drill:
     who     "solo" = by yourself (a tee, a net, a wall, a fence)   "partner" = with a coach, parent or teammate
     pos     hitting, pitching, catcher, first, middle (2B + SS), third, outfield, throwing (everyone), running
     gear    what you need            dose    how much to do
     why     what it builds           steps   how to do it
     cues    coaching points          avoid   common mistakes
     harder  how to progress it       yt      YouTube search for a demo video
     fixes   swing problems it helps (the Swing lab uses these to build your drill plan):
             head, lunge, early_open, no_sep, sequence, cast, extension, block, collapse,
             stride_open, stride_closed, overstride, posture, balance, slow, load, stance */

const DRILL_POSITIONS = [
  ['hitting', 'Hitting'], ['pitching', 'Pitching'], ['catcher', 'Catcher'], ['first', 'First base'], ['middle', '2B / SS'],
  ['third', 'Third base'], ['outfield', 'Outfield'], ['throwing', 'Throwing'], ['running', 'Base running']
];

const DRILLS = [
  /* ============================ HITTING — ALONE ============================ */
  { id: 'tee-zones', n: 'Tee work: inside, middle, outside', pos: ['hitting'], who: 'solo', gear: 'Tee, a bucket of balls, a net or fence',
    dose: '3 rounds of 10 swings', why: 'Builds one repeatable swing and teaches you where to meet the ball for each pitch location.',
    steps: ['Middle pitch: tee belt-high, even with your front hip. Hit 10 line drives back up the middle.',
      'Inside pitch: move the tee closer to you and a little farther out in front, near your front foot. Hit 10 to your pull side.',
      'Outside pitch: move the tee away from you and back toward the middle of your stance. Hit 10 to the opposite field.',
      'Take a full reset between swings: stance, load, stride, swing, hold your finish.'],
    cues: ['Inside = out front, outside = let it travel deeper', 'Hit hard line drives, not fly balls or grounders', 'Every swing is a game swing — no lazy reps'],
    avoid: ['Using the same contact point for every location', 'Rushing through reps without resetting'],
    harder: 'Change the height too (knees, belt, letters), or have someone call the location right before you swing.',
    fixes: ['extension', 'cast', 'head'], yt: 'baseball tee drill inside middle outside contact points' },
  { id: 'two-tee', n: 'Two-tee drill', pos: ['hitting'], who: 'solo', gear: '2 tees (or a tee and a cone), balls, a net',
    dose: '3 rounds of 8 swings', why: 'Trains a long, level path through the hitting zone so the barrel stays on the line of the pitch.',
    steps: ['Put the ball on the first tee at your normal contact point.',
      'Set a second tee without a ball 12–18 inches in front of it, toward the pitcher, a little lower than the ball.',
      'Swing so your barrel goes through the ball and over the front tee without hitting it.',
      'Finish with both arms extended toward the pitcher before you rotate around.'],
    cues: ['Stay through the ball — extend to the front tee', 'Knob to the ball, then barrel through it'],
    avoid: ['Chopping down on the ball', 'Pulling off early so the barrel cuts across the zone'],
    harder: 'Move the front tee farther out, or hit a ball off both tees in one swing (front tee a little higher).',
    fixes: ['extension', 'posture', 'early_open'], yt: 'two tee drill baseball swing path' },
  { id: 'inside-out-tee', n: 'Inside-out tee', pos: ['hitting'], who: 'solo', gear: 'Tee, balls, a net',
    dose: '3 rounds of 8 swings', why: 'Keeps your hands inside the ball so the barrel doesn\'t swing out wide (casting).',
    steps: ['Set the tee on the inner part of the plate, a little deeper than normal (even with the middle of your stance).',
      'Aim to hit line drives to the opposite field.',
      'Your hands lead the knob toward the ball, close to your body, and the barrel follows.'],
    cues: ['Knob to the ball', 'Back elbow slots down to your side', 'Hit the inside half of the ball'],
    avoid: ['Pushing the hands away from your body', 'Rolling your wrists before contact'],
    harder: 'Put a second tee (or a bucket) just outside the plate so a wide swing hits it.',
    fixes: ['cast', 'extension'], yt: 'inside out swing tee drill baseball' },
  { id: 'fence-drill', n: 'Fence drill', pos: ['hitting'], who: 'solo', gear: 'A bat and a fence, wall or net',
    dose: '3 sets of 10 dry swings', why: 'The fastest fix for casting: a long, wide swing hits the fence, a tight swing doesn\'t.',
    steps: ['Stand facing the fence, like the fence is home plate.',
      'Set the knob of the bat on your belly with the end touching the fence, then take your stance at that distance.',
      'Take slow swings without touching the fence, then speed up as you get it right.',
      'Step a few inches closer once you can do 10 in a row cleanly.'],
    cues: ['Hands stay close — elbow to your side', 'Turn the barrel, don\'t push it out'],
    avoid: ['Leaning back to make room', 'Dropping the back shoulder to get under it'],
    harder: 'Move closer to the fence, or do it with a full stride and at game speed.',
    fixes: ['cast', 'collapse'], yt: 'fence drill baseball hitting casting' },
  { id: 'one-hand', n: 'One-hand drills (top and bottom hand)', pos: ['hitting'], who: 'solo', gear: 'A light or short bat, tee, balls, a net',
    dose: '10 swings each hand, 2 rounds', why: 'Teaches each hand its job: the bottom hand pulls the knob to the ball, the top hand drives through it.',
    steps: ['Choke up or use a short bat. Put your free hand on your chest.',
      'Bottom hand (lead hand): pull the knob to the ball, extend through contact, keep the wrist firm.',
      'Top hand: palm up at contact, drive through the middle of the ball.',
      'Finish with 5 two-hand swings to put it together.'],
    cues: ['Short and quick to the ball', 'Firm wrist at contact'],
    avoid: ['Using a heavy bat so you drop the barrel', 'Swinging around the ball with the top hand'],
    harder: 'Do it off soft toss instead of a tee.', fixes: ['cast', 'extension'], yt: 'one hand hitting drills top hand bottom hand' },
  { id: 'stride-freeze', n: 'Stride-and-freeze (launch check)', pos: ['hitting'], who: 'solo', gear: 'A bat (a mirror or phone camera helps)',
    dose: '10 reps, then 10 tee swings', why: 'Checks your position when your front foot lands — the moment most swing problems start.',
    steps: ['Take your load and stride like it\'s a real pitch, then freeze when your front foot lands.',
      'Hold 2 seconds and check: head over the middle of your stance, weight about 60% on the back leg, hands back, front shoulder closed.',
      'Then swing from that position.', 'Film it from the side a few times to see it.'],
    cues: ['Land soft — "on the ball of the foot"', 'Head stays still over your belly button', 'Front shoulder stays pointed at the pitcher'],
    avoid: ['Drifting your head forward with the stride', 'Opening the front shoulder as the foot lands'],
    harder: 'Do it with soft toss: freeze, then the partner tosses.', fixes: ['lunge', 'head', 'early_open', 'load', 'no_sep', 'overstride'], yt: 'stride and hold drill baseball hitting load' },
  { id: 'hip-turn', n: 'Bat-behind-the-back hip turns', pos: ['hitting'], who: 'solo', gear: 'A bat',
    dose: '3 sets of 10', why: 'Teaches the hips to start the swing while the shoulders stay closed for a split second — that gap is where power comes from.',
    steps: ['Hold the bat behind your back in the bend of both elbows.',
      'Get in your stance, load and stride.',
      'Turn your hips hard toward the pitcher while your shoulders and the bat stay closed for a beat.',
      'Then let the shoulders follow and finish facing the pitcher, back foot turned.'],
    cues: ['Hips first, shoulders second', 'Feel the stretch across your stomach', 'Back knee drives toward the front knee'],
    avoid: ['Turning everything at once', 'Spinning on the back heel without moving the hips forward'],
    harder: 'Add a resistance band around your waist anchored behind you.', fixes: ['sequence', 'no_sep', 'early_open'], yt: 'bat behind back hip rotation drill hitting' },
  { id: 'step-back', n: 'Step-back rhythm drill', pos: ['hitting'], who: 'solo', gear: 'Tee, balls, a net',
    dose: '3 rounds of 8 swings', why: 'Teaches you to load into your back leg and move forward with rhythm instead of being stiff.',
    steps: ['Start with your feet together near the back of the box.',
      'Step back with your back foot and feel your weight sink into the back hip.',
      'Stride forward and swing in one smooth motion.'],
    cues: ['Sink into the back hip', 'Smooth, not fast, until contact'], avoid: ['Stepping back without loading the hip', 'Lunging on the stride'],
    harder: 'Do it off front toss.', fixes: ['load', 'slow'], yt: 'step back drill baseball hitting rhythm load' },
  { id: 'balance-board', n: '2x4 balance swings', pos: ['hitting'], who: 'solo', gear: 'A 2x4 board (or a line on the ground), tee, balls',
    dose: '3 rounds of 8 swings', why: 'Builds balance and a straight stride — you have to stay on the board to finish.',
    steps: ['Lay a 2x4 on the ground pointing at the pitcher. Stand on it in your stance.',
      'Hit off a tee and stay on the board through your finish.',
      'Hold the finish for 3 seconds on every swing.'],
    cues: ['Stride straight at the pitcher', 'Stay in your legs'], avoid: ['Falling off toward the plate or away from it', 'Swinging at half speed'],
    harder: 'Do it off soft toss.', fixes: ['balance', 'stride_open', 'stride_closed', 'lunge'], yt: '2x4 balance beam hitting drill baseball' },
  { id: 'head-still', n: 'Head-still tee (eyes on the dot)', pos: ['hitting'], who: 'solo', gear: 'Tee, balls with a dot marked on them, a net',
    dose: '3 rounds of 10', why: 'Keeps your head still and your eyes on the ball through contact.',
    steps: ['Mark a dot on the back of each ball with a marker.',
      'Set the ball so the dot faces you. Watch the dot until the ball is gone.',
      'After contact, keep your eyes on the tee for a split second before looking up.'],
    cues: ['See the bat hit the dot', 'Chin stays down, head stays still'], avoid: ['Pulling your head toward the pitcher to watch the ball fly', 'Big head movement during the stride'],
    harder: 'Use smaller balls (golf-ball size wiffle balls) off a tee.', fixes: ['head', 'posture'], yt: 'keep head still hitting drill baseball' },
  { id: 'high-low-tee', n: 'High and low tee', pos: ['hitting'], who: 'solo', gear: 'Tee, balls, a net',
    dose: '2 rounds of 8 high and 8 low', why: 'Teaches you to use your legs and posture to match pitch height instead of dropping the back shoulder or the barrel.',
    steps: ['High: tee at the letters. Hit line drives without dropping the back shoulder.',
      'Low: tee at the knees. Bend your knees and hinge to get down to it — keep the barrel above your hands.',
      'Alternate a high and a low swing.'],
    cues: ['Legs adjust to the height', 'Stay on top of the high ball'], avoid: ['Uppercutting the high pitch', 'Dropping the hands for the low pitch'],
    harder: 'Have someone call "high" or "low" right before you swing.', fixes: ['collapse', 'posture'], yt: 'high tee low tee hitting drill' },
  { id: 'stride-line', n: 'Stride line drill', pos: ['hitting'], who: 'solo', gear: 'A bat or tape on the ground, tee, balls',
    dose: '3 rounds of 8', why: 'Fixes stepping "in the bucket" (away from the plate) or crossing over too far.',
    steps: ['Lay a bat on the ground from your front foot pointing straight at the pitcher.',
      'Take your stride and land with your front foot on or right next to the line.',
      'Mark your normal stride length with tape so you land in the same spot every time.'],
    cues: ['Stride straight at the pitcher', 'Same landing spot every time'], avoid: ['Opening your front foot too early', 'A different stride length every swing'],
    harder: 'Do it off soft toss or front toss.', fixes: ['stride_open', 'stride_closed', 'overstride'], yt: 'stride direction drill baseball hitting' },
  { id: 'front-block', n: 'Front leg block drill', pos: ['hitting'], who: 'solo', gear: 'Tee, balls, a net',
    dose: '3 rounds of 8', why: 'A firm front leg stops your forward move and turns it into rotation — more bat speed, less lunging.',
    steps: ['Stride and land with a slightly bent front knee.',
      'As you swing, push into the ground and straighten (firm up) the front leg.',
      'Your hips turn over the firm front leg, and your head stays behind the ball.'],
    cues: ['Stride, then post up', 'Push the ground away with your front foot'], avoid: ['Keeping the front knee bent and sliding forward', 'Locking the knee before the foot lands'],
    harder: 'Do it with a longer stride, or off front toss.', fixes: ['block', 'lunge'], yt: 'front leg block drill hitting baseball' },
  { id: 'hold-finish', n: 'Hold the finish', pos: ['hitting'], who: 'solo', gear: 'Tee, balls, a net',
    dose: 'Every swing in a round of 10', why: 'If you can\'t hold your finish, something in the swing was off balance.',
    steps: ['Take a full swing and hold the finish for 3 seconds.',
      'Check: back foot turned up on the toe, belly button facing the pitcher, head still over your belly button, bat wrapped around your back.'],
    cues: ['Finish tall and balanced', 'Freeze like a photo'], avoid: ['Falling toward the plate', 'Letting go of the bat with the top hand too early (unless that\'s your style)'],
    harder: 'Close your eyes during the hold.', fixes: ['balance'], yt: 'hold your finish hitting balance drill' },
  { id: 'shadow-swings', n: 'Mirror shadow swings', pos: ['hitting'], who: 'solo', gear: 'A bat and a mirror (or your phone camera)',
    dose: '10 slow swings + 10 at full speed', why: 'Slow checkpoints teach your body what a good position feels like before you speed it up.',
    steps: ['Swing in slow motion in front of a mirror and stop at five checkpoints: stance, load, foot plant, contact, finish.',
      'Fix anything that looks off at each stop.', 'Finish with 10 full-speed dry swings keeping the same positions.'],
    cues: ['Slow is smooth, smooth is fast', 'Match the checkpoints every time'], avoid: ['Rushing through the checkpoints', 'Only doing fast swings'],
    harder: 'Film yourself from the side and compare to the Swing lab key frames.', fixes: ['posture', 'load', 'stance'], yt: 'shadow swing drill baseball mirror checkpoints' },
  { id: 'overload-underload', n: 'Heavy and light bat swings', pos: ['hitting'], who: 'solo', gear: 'Your bat plus a slightly heavier and a slightly lighter bat',
    dose: '2 sets: 5 heavy, 5 light, 5 game bat', why: 'Swinging a slightly heavier and slightly lighter bat builds bat speed.',
    steps: ['Use bats about 10–20% heavier and lighter than your game bat.',
      'Take 5 full-effort dry swings with the heavy bat, 5 with the light bat, then 5 with your game bat.',
      'Rest 1 minute between sets. Keep perfect form — stop if your swing gets sloppy.'],
    cues: ['Every swing at full effort', 'Same mechanics with every bat'], avoid: ['Using a bat so heavy your swing changes', 'Doing too many — quality over quantity'],
    harder: 'Do it 3 times a week for 6 weeks and test your exit velocity before and after.', fixes: ['slow'], yt: 'overload underload bat training baseball' },

  /* ============================ HITTING — WITH A PARTNER ============================ */
  { id: 'front-toss', n: 'Front toss', pos: ['hitting'], who: 'partner', gear: 'An L-screen, balls, a net or open field',
    dose: '3 rounds of 10', why: 'The closest thing to a real pitch without a pitcher — works timing, direction and contact.',
    steps: ['Your partner sits or kneels behind an L-screen 15–20 feet in front of you.',
      'They toss firm, underhand strikes.', 'Hit line drives back up the middle.'],
    cues: ['Load early, be on time', 'Hit it right back at the screen (safely)'], avoid: ['The tosser standing without a screen', 'Swinging at bad tosses'],
    harder: 'Ask for different speeds and locations.', fixes: ['head', 'sequence'], yt: 'front toss hitting drill baseball' },
  { id: 'side-toss', n: 'Side soft toss', pos: ['hitting'], who: 'partner', gear: 'Balls and a net',
    dose: '3 rounds of 10', why: 'Lots of good reps fast, working your contact point and extension.',
    steps: ['Partner kneels at a 45° angle in front of you, off to the side of the plate — safely out of the swing path.',
      'They toss the ball into your contact zone (out in front of your front hip).', 'Hit line drives into the net.'],
    cues: ['Let the toss come to you', 'Extend through the ball'], avoid: ['Tossing too far back (you\'ll hit late)', 'The tosser standing in front of the net'],
    harder: 'Ask for quick tosses in a row.', fixes: ['extension', 'cast'], yt: 'soft toss drill baseball hitting' },
  { id: 'rapid-fire', n: 'Rapid-fire toss', pos: ['hitting'], who: 'partner', gear: 'Balls and a net',
    dose: '3 rounds of 8 quick swings', why: 'Builds quick hands and a short swing — you have to reset and fire fast.',
    steps: ['Partner tosses a ball every 2–3 seconds.', 'Reset to your launch position and swing every time.', 'Keep your swing short and compact as you get tired.'],
    cues: ['Short to the ball', 'Reset fast, swing hard'], avoid: ['Swinging without resetting your hands', 'Losing your posture when you get tired'],
    harder: 'Make the tosses faster or go to 12 in a row.', fixes: ['slow', 'load'], yt: 'rapid fire soft toss drill quick hands' },
  { id: 'call-location', n: 'Call-the-location toss', pos: ['hitting'], who: 'partner', gear: 'Balls, a net or L-screen',
    dose: '3 rounds of 8', why: 'Teaches you to cover the whole plate and move your contact point for each location.',
    steps: ['Partner tosses and calls "in", "middle" or "out" (or "up"/"down") as the ball leaves their hand.',
      'Pull the inside pitch, hit the middle pitch back up the middle, and take the outside pitch the other way.'],
    cues: ['Inside = out front', 'Outside = let it travel'], avoid: ['Guessing before the call', 'Trying to pull everything'],
    harder: 'Have them call it later and later.', fixes: ['extension'], yt: 'pitch location hitting drill in middle out' },
  { id: 'two-color', n: 'Two-color ball recognition', pos: ['hitting'], who: 'partner', gear: 'Balls in two colors (or marked with a colored dot)',
    dose: '3 rounds of 10', why: 'Trains pitch recognition and patience — you decide late whether to swing.',
    steps: ['Partner mixes two colors of balls and front-tosses.', 'Swing only at one color (for example red). Take the other color with a still head.',
      'Switch the swing color every round.'],
    cues: ['See it early, decide late', 'Head stays still on takes too'], avoid: ['Swinging early before you see the color', 'Lunging forward on takes'],
    harder: 'Use colored dots instead of full colors.', fixes: ['head', 'lunge'], yt: 'two color ball pitch recognition hitting drill' },
  { id: 'bunting', n: 'Bunting: sacrifice and drag', pos: ['hitting'], who: 'partner', gear: 'Balls; a partner throwing from 30–40 feet',
    dose: '10 sacrifice bunts, 10 bunts for a hit', why: 'Bunting wins games — and most players are bad at it because they never practice.',
    steps: ['Sacrifice: square around or pivot early, bat at the top of the zone, knees bent.',
      'Catch the ball with the barrel — let it come to the bat, don\'t push at it.',
      'Aim for the first- and third-base lines, 10–15 feet out.', 'Drag/push bunt: show late and start running as you make contact.'],
    cues: ['Bat at the top of the strike zone', 'Bend your knees for low pitches, not your arms'], avoid: ['Stabbing at the ball', 'Bunting pitches above the bat'],
    harder: 'Set targets (a glove or a towel) on each line.', fixes: [], yt: 'how to bunt baseball sacrifice drag bunt drill' },
  { id: 'live-timing', n: 'Timing with a pitcher or machine', pos: ['hitting'], who: 'partner', gear: 'A pitcher or pitching machine, balls, a net or field',
    dose: '3 rounds of 8 pitches', why: 'Timing is everything — learn when to start your load against real speed.',
    steps: ['Pitcher or machine at game speed (move closer for more speed).',
      'Start your load when the pitcher\'s hand separates from the glove.', 'Count "load… stride… hit" and be on time.'],
    cues: ['Early to load, on time to hit', 'Hit the fastball, adjust to the rest'], avoid: ['Starting late and rushing', 'Starting too early and stopping'],
    harder: 'Mix speeds (fastball / change-up).', fixes: ['slow', 'load'], yt: 'timing drill hitting baseball load when to start' },

  /* ============================ PITCHING ============================ */
  { id: 'towel-drill', n: 'Towel drill', pos: ['pitching'], who: 'solo', gear: 'A hand towel and a target (a glove on a chair or bucket)',
    dose: '3 sets of 10 deliveries', why: 'Full pitching delivery without throwing — builds extension and a good arm path with no arm stress.',
    steps: ['Hold a hand towel by one corner like a ball.', 'Set a target at your stride length plus one arm length in front of you.',
      'Go through your full delivery and snap the towel down on the target.'],
    cues: ['Stride long and reach out front', 'Chest over the front knee at release', 'Finish with your back leg coming through'],
    avoid: ['Short-arming it to hit the target', 'Falling off to the side'], harder: 'Move the target a few inches farther to force more extension.',
    fixes: [], yt: 'towel drill pitching mechanics' },
  { id: 'balance-point', n: 'Balance point hold', pos: ['pitching'], who: 'solo', gear: 'Nothing (a mirror helps)',
    dose: '3 sets of 5 holds', why: 'A balanced leg lift leads to a consistent release and better control.',
    steps: ['Lift your front leg to the top of your balance point and hold 3 seconds.', 'Stay tall with your weight on the middle of your back foot.',
      'Then stride slowly and finish your delivery.'], cues: ['Tall and quiet at the top', 'Weight on the back foot, not the toes'],
    avoid: ['Leaning back toward second base', 'Rushing forward before you\'re balanced'], harder: 'Do the holds with your eyes closed.',
    fixes: [], yt: 'balance point drill pitching' },
  { id: 'rocker-net', n: 'Rocker throws into a net', pos: ['pitching'], who: 'solo', gear: 'A net and balls',
    dose: '15–20 throws at 60–75% effort', why: 'Works rhythm, weight transfer and arm path with a short, simple motion.',
    steps: ['Start in your stride position with the front foot down.', 'Rock your weight back and forth twice to feel the shift.',
      'On the third rock, throw into the net.'], cues: ['Weight back, then drive forward', 'Glove stays in front of your chest'],
    avoid: ['Throwing with just your arm', 'Letting the glove fly open'], harder: 'Throw to a target spot on the net.', fixes: [], yt: 'rocker drill pitching' },
  { id: 'hip-lead', n: 'Hip-lead drill', pos: ['pitching'], who: 'solo', gear: 'Nothing, or a net and balls',
    dose: '3 sets of 5', why: 'Leading with the front hip builds momentum and hip-shoulder separation for velocity.',
    steps: ['From your leg lift, start moving toward the plate with your front hip first (your "side" leads, not your chest).',
      'Keep your shoulders closed as you stride.', 'Land, then let the shoulders rotate and throw (or dry-throw).'],
    cues: ['Hip leads, shoulders stay closed', 'Stride toward home, not across'], avoid: ['Opening your chest early', 'Falling forward before the hip leads'],
    harder: 'Add a throw into a net at full effort.', fixes: [], yt: 'hip lead drill pitching' },
  { id: 'command-target', n: 'Command targets', pos: ['pitching'], who: 'solo', gear: 'A net with a strike zone, or tape a box on a wall',
    dose: '25 pitches', why: 'Command wins more games than velocity.',
    steps: ['Tape a strike zone on a wall or net with four corners marked.', 'Call a spot before every pitch, then throw to it.',
      'Keep score: 1 point for the zone, 2 for the called corner.'], cues: ['Pick a small target', 'Same release every pitch'],
    avoid: ['Aiming (steering) the ball', 'Throwing without a target'], harder: 'Play a game: 3 balls and you\'re out, 3 hits on the corners wins.',
    fixes: [], yt: 'pitching command drill target' },
  { id: 'flat-ground', n: 'Flat-ground bullpen', pos: ['pitching'], who: 'partner', gear: 'A catcher and balls',
    dose: '20–30 pitches at 60–75% effort', why: 'Works mechanics and command with less stress than the mound.',
    steps: ['Throw on flat ground at 50–60 feet.', 'Work fastball command first: glove side, arm side, down.',
      'Add off-speed pitches only after your fastball is sharp.', 'Log the pitches in the arm-care log.'],
    cues: ['Command first, velocity second', 'Finish every pitch'], avoid: ['Throwing max effort', 'Skipping your arm-care warm-up'],
    harder: 'Your catcher calls the pitch and location every time.', fixes: [], yt: 'flat ground bullpen pitching drill' },
  { id: 'pfp', n: 'Pitcher fielding practice (PFP)', pos: ['pitching'], who: 'partner', gear: 'Balls; a first baseman or a net',
    dose: '15 minutes', why: 'Pitchers are the fifth infielder — clean fielding saves runs.',
    steps: ['Partner rolls bunts and comebackers.', 'Field it, set your feet toward the base, and make a firm throw.',
      'On balls to the right side, sprint to cover first and take the throw on the inside of the bag.'],
    cues: ['Feet first, then throw', 'Cover first on every ball to your left'], avoid: ['Throwing off-balance', 'Standing and watching a ground ball to the right side'],
    harder: 'Add a runner and make it game speed.', fixes: [], yt: 'pitcher fielding practice pfp drills' },
  { id: 'pickoffs', n: 'Pickoff moves and slide step', pos: ['pitching'], who: 'partner', gear: 'A first baseman (partner) and balls',
    dose: '10 pickoffs each side, 10 slide steps', why: 'Holding runners keeps them from stealing easy bases.',
    steps: ['From the set, step off the rubber and throw to first.', 'Practice your quick pickoff move to first and a spin move to second.',
      'Practice a slide step to the plate (1.3 seconds or less to the catcher).'], cues: ['Vary your hold time', 'Quick feet, firm throw'],
    avoid: ['The same timing every pitch', 'Balking — know the rules for your league'], harder: 'Have a runner try to steal.', fixes: [], yt: 'pitcher pickoff move drill slide step' },

  /* ============================ CATCHER ============================ */
  { id: 'block-reps', n: 'Blocking reps', pos: ['catcher'], who: 'solo', gear: 'Full gear; a wall and tennis balls (optional)',
    dose: '3 sets of 10 (middle, left, right)', why: 'Keeps balls in the dirt in front of you so runners can\'t advance.',
    steps: ['From your crouch, drop both knees to the ground at the same time.', 'Glove fills the gap between your legs, chin tucked, shoulders rounded forward.',
      'For balls to the side, step and turn your body so the ball bounces back toward home plate.',
      'Throw tennis balls at a wall so they short-hop back to you for live reps.'], cues: ['Knees down, glove down, chin down', 'Angle your chest to home'],
    avoid: ['Catching the ball instead of blocking it', 'Turning your head away'], harder: 'Recover the ball and pop up to throw after each block.',
    fixes: [], yt: 'catcher blocking drill' },
  { id: 'catcher-transfer', n: 'Transfer and footwork (pop time)', pos: ['catcher'], who: 'solo', gear: 'Full gear, balls, a net',
    dose: '3 sets of 8', why: 'A quick transfer and clean footwork cut your pop time.',
    steps: ['From your secondary stance, toss a ball into your glove.', 'Bring the glove to your throwing hand at the chest and find a four-seam grip.',
      'Replace your feet (or jump-pivot) and throw through the net toward second.', 'Time a few with the app\'s stopwatch and log them as pop time.'],
    cues: ['Glove to the chest, not the ear', 'Short, quick feet'], avoid: ['Long arm swing on the throw', 'Standing up before you get the ball'],
    harder: 'Have a partner throw the pitch and time glove to glove.', fixes: [], yt: 'catcher transfer footwork drill pop time' },
  { id: 'catcher-mobility', n: 'Catcher hip mobility routine', pos: ['catcher'], who: 'solo', gear: 'Nothing',
    dose: '8 minutes, every day', why: 'Mobile hips let you get lower, block better and stay healthy through a long season.',
    steps: ['Deep squat hold: 3 × 30 seconds, elbows pushing the knees out.', '90/90 hip switches: 2 × 10.',
      'Adductor rock-backs: 2 × 10 per side.', 'Catcher\'s stance holds on one heel then the other: 2 × 20 seconds.'],
    cues: ['Chest up, heels down', 'Move slowly'], avoid: ['Bouncing in the stretches', 'Skipping it on game days'],
    harder: 'Hold the deep squat with light weight.', fixes: [], yt: 'catcher hip mobility routine' },
  { id: 'framing', n: 'Receiving and framing', pos: ['catcher'], who: 'partner', gear: 'Full gear, a partner throwing from 30–45 feet',
    dose: '3 rounds of 10', why: 'Good receiving keeps strikes as strikes and steals a few more.',
    steps: ['Partner throws to the edges of the zone.', 'Catch the ball with a quiet glove — beat the ball to the spot.',
      'On edge pitches, catch the outside of the ball and "stick" it — hold for one second.'], cues: ['Quiet body, soft hands', 'Stick it, don\'t jerk it'],
    avoid: ['Stabbing or jerking the glove into the zone', 'Moving your head'], harder: 'Have them throw harder or use a machine.', fixes: [], yt: 'catcher framing receiving drill' },
  { id: 'block-live', n: 'Blocking balls in the dirt', pos: ['catcher'], who: 'partner', gear: 'Full gear, balls (start with tennis balls)',
    dose: '3 sets of 8', why: 'Live short hops teach you to read the bounce and react.',
    steps: ['Partner throws short hops to your left, middle and right from 30–40 feet.', 'Block with your chest angled back toward home.',
      'Find the ball and recover it quickly.'], cues: ['Beat the ball to the spot', 'Soft chest, round shoulders'],
    avoid: ['Reaching with the glove', 'Letting it bounce off to the side'], harder: 'Mix in balls you should catch and have them call a runner.',
    fixes: [], yt: 'catcher blocking drill balls in the dirt' },
  { id: 'catcher-popups', n: 'Catcher pop-ups', pos: ['catcher'], who: 'partner', gear: 'Mask, glove; a partner (a tennis racket and tennis balls works great)',
    dose: '10 pop-ups', why: 'Pop-ups spin back toward the infield — catchers need special reps.',
    steps: ['Partner throws or hits a high pop-up near home.', 'Pop up, find the ball, turn your back to the infield.',
      'Toss your mask away from where the ball is going and catch it above your head.'], cues: ['Back to the infield', 'Ball drifts back toward the field'],
    avoid: ['Dropping the mask where you\'ll trip on it', 'Drifting under it too early'], harder: 'Add a fence or dugout nearby.', fixes: [], yt: 'catcher pop up drill' },

  /* ============================ INFIELD (1B / 2B / SS / 3B) ============================ */
  { id: 'wall-ball', n: 'Wall ball short hops', pos: ['first', 'middle', 'third'], who: 'solo', gear: 'A glove, a wall, a tennis or rubber ball',
    dose: '3 rounds of 20', why: 'Hundreds of hops in a few minutes — soft hands and quick feet.',
    steps: ['Throw the ball against a wall so it comes back as a ground ball or short hop.', 'Field it with your glove out in front, then throw it again.',
      'Mix forehands, backhands and short hops.'], cues: ['Glove out front, eyes down', 'Give with the ball — soft hands'],
    avoid: ['Fielding between your feet', 'Standing flat-footed'], harder: 'Throw harder or stand closer.', fixes: [], yt: 'wall ball drill infield' },
  { id: 'range-steps', n: 'Range steps: drop step and crossover', pos: ['first', 'middle', 'third'], who: 'solo', gear: 'Cones or balls as markers',
    dose: '3 rounds of 6 each way', why: 'Your first step decides how many balls you get to.',
    steps: ['Start in your ready position.', 'Crossover step to your left, sprint 5 yards to a cone and break down like you\'re fielding.',
      'Repeat to the right, then add a drop step back for balls over your head.'], cues: ['Stay low on the first step', 'Break down before you field'],
    avoid: ['Standing up on your first step', 'False steps backward'], harder: 'Have a partner point a direction at random.', fixes: [], yt: 'infield first step crossover drill' },
  { id: 'alligator', n: 'Alligator hands', pos: ['first', 'middle', 'third'], who: 'partner', gear: 'Gloves and balls',
    dose: '3 rounds of 15', why: 'Teaches two-handed fielding and funneling the ball to your belly for a quick throw.',
    steps: ['Partner rolls ground balls from 15–20 feet.', 'Field with the glove down and open, throwing hand on top like an alligator\'s mouth.',
      'Funnel the ball to your belly button, then come up throwing.'], cues: ['Glove down early', 'Two hands, then funnel'],
    avoid: ['Snapping the top hand down too early', 'Fielding with stiff arms'], harder: 'Harder rolls, then short hops.', fixes: [], yt: 'alligator hands fielding drill' },
  { id: 'backhand-forehand', n: 'Backhand and forehand', pos: ['first', 'middle', 'third'], who: 'partner', gear: 'Gloves and balls',
    dose: '3 rounds of 10 each side', why: 'Most hard-hit balls aren\'t right at you.',
    steps: ['Partner rolls or hits balls to your glove side and your backhand side.', 'Backhand: stay low, glove open, field it even with your front foot.',
      'Forehand: open up, get the glove out front and field it on the move.', 'Set your feet and throw after each one.'],
    cues: ['Stay low through the ball', 'Field it out front'], avoid: ['Turning the glove over too early on the backhand', 'Standing up before you catch it'],
    harder: 'Make them farther so you have to dive or throw on the run.', fixes: [], yt: 'backhand forehand infield drill' },
  { id: 'slow-roller', n: 'Slow roller: charge and throw', pos: ['middle', 'third'], who: 'partner', gear: 'Gloves, balls, a first baseman or a net',
    dose: '10–15 reps', why: 'Slow rollers are the hardest play for third basemen and shortstops.',
    steps: ['Partner rolls slow balls.', 'Charge hard, field it with the glove (barehand only if it\'s stopped or barely moving).',
      'Catch it as your left foot lands (right-handed thrower) and throw on the run, sidearm.'], cues: ['Charge hard, under control', 'Field and throw in one motion'],
    avoid: ['Stopping to set your feet', 'Barehanding a ball that\'s still moving fast'], harder: 'Time it with a runner.', fixes: [], yt: 'slow roller infield drill charge' },
  { id: 'short-hop-picks', n: 'Short-hop picks at first', pos: ['first'], who: 'partner', gear: 'First base glove, balls',
    dose: '3 rounds of 10', why: 'Saving bad throws turns errors into outs.',
    steps: ['Partner throws short hops at you from 20–30 feet.', 'Stretch toward the throw and scoop through the ball in one motion.',
      'Pick the long hop out front and the short hop right at the bounce.'], cues: ['Scoop, don\'t stab', 'Stretch late, after you read the throw'],
    avoid: ['Stretching before you see the throw', 'Catching the in-between hop'], harder: 'Mix in throws to either side.', fixes: [], yt: 'first base scoop short hop drill' },
  { id: 'first-footwork', n: 'First base footwork to the bag', pos: ['first'], who: 'solo', gear: 'A base or a marker',
    dose: '10 reps each side', why: 'Getting to the bag fast and set up right makes every play easier.',
    steps: ['From your fielding position, sprint to the bag.', 'Find the bag with your heel, then face the infielder throwing to you.',
      'Stretch toward the throw only after it\'s released.'], cues: ['Get there early and square up', 'Stretch late'], avoid: ['Stretching before the throw', 'Getting to the bag late and off balance'],
    harder: 'Add a partner throwing from each infield spot.', fixes: [], yt: 'first base footwork drill' },
  { id: 'first-stretch', n: 'Stretch and receive (off-line throws)', pos: ['first'], who: 'partner', gear: 'Gloves, balls',
    dose: '3 rounds of 10', why: 'Teaches you when to stay on the bag and when to come off it.',
    steps: ['Partner throws from shortstop, second and third distances — some off target.', 'Stay on the bag and stretch for throws you can reach.',
      'Come off the bag for wide throws and try to tag the runner.'], cues: ['Catch it first, then the bag', 'Read the throw early'],
    avoid: ['Staying on the bag for an unreachable throw', 'Stretching the wrong leg'], harder: 'Add a runner.', fixes: [], yt: 'first base receiving throws drill' },
  { id: 'dp-feeds', n: 'Double-play feeds (2B / SS)', pos: ['middle'], who: 'partner', gear: 'Gloves, balls, second base',
    dose: '10 feeds of each type', why: 'A good feed makes the turn easy.',
    steps: ['Partner covers second. Field a ground ball and feed them.', 'Close to the bag: underhand flip, showing the ball.',
      'Medium distance: backhand flip or a short sidearm toss. Far away: firm chest-high throw.'], cues: ['Show the ball on flips', 'Chest-high target'],
    avoid: ['Rushing the feed and throwing it away', 'Hiding the ball from your partner'], harder: 'Add game speed and a runner.', fixes: [], yt: 'double play feeds drill second base shortstop' },
  { id: 'dp-pivots', n: 'Turning two at second', pos: ['middle'], who: 'partner', gear: 'Gloves, balls, second base',
    dose: '10 turns each way', why: 'Clean footwork at the bag keeps you out of the runner\'s way.',
    steps: ['Partner feeds you at the bag.', 'Second baseman: step on the bag and throw across it or step back off it.',
      'Shortstop: drag your right foot across the corner of the bag and throw on the way through.'], cues: ['Feet to the ball first', 'Get off the bag after the throw'],
    avoid: ['Standing on the bag waiting', 'Throwing across your body off-balance'], harder: 'Have a runner come in.', fixes: [], yt: 'turning double play pivot second base shortstop' },
  { id: 'hot-corner', n: 'Hot-corner reactions (third base)', pos: ['third'], who: 'partner', gear: 'Glove; tennis balls to start',
    dose: '3 rounds of 10', why: 'At third you get hard-hit balls with no time — reactions are everything.',
    steps: ['Partner throws or hits hard grounders and liners from 40–50 feet (start with tennis balls).', 'Stay low with your glove out front.',
      'If you can\'t catch it clean, knock it down in front of you and recover to throw.'], cues: ['Low and ready before every pitch', 'Knock it down'],
    avoid: ['Standing up tall', 'Turning your head away'], harder: 'Move closer or use real balls.', fixes: [], yt: 'third base reaction drill' },
  { id: 'long-throws-3b', n: 'Throws across the diamond', pos: ['third', 'middle'], who: 'partner', gear: 'Gloves, balls, a first baseman or partner at 120 feet',
    dose: '15 throws', why: 'Builds a strong, accurate throw from the left side of the infield.',
    steps: ['Field a ground ball (or start from a fielded position).', 'Step toward your target with a quick crow-hop or shuffle.',
      'Throw on a line to the first baseman\'s chest.'], cues: ['Feet to the target', 'Throw through the target, not to it'],
    avoid: ['Throwing with your feet still', 'Aiming the ball'], harder: 'Add a runner and a clock (about 4.2 seconds home to first).', fixes: [], yt: 'infield throwing drill across the diamond' },

  /* ============================ OUTFIELD ============================ */
  { id: 'drop-step-go', n: 'Drop step and go', pos: ['outfield'], who: 'solo', gear: 'Cones or markers',
    dose: '3 rounds of 6 each side', why: 'A fast first step back gets you to balls over your head.',
    steps: ['From the ready position, drop step at 45° back to one side.', 'Crossover and sprint 15 yards on a line.',
      'Look over your shoulder like you\'re tracking the ball.'], cues: ['Open the hip, don\'t backpedal', 'Run on your toes so your eyes stay still'],
    avoid: ['Backpedaling', 'False step forward first'], harder: 'Have a partner point a direction and add a ball.', fixes: [], yt: 'outfield drop step drill' },
  { id: 'crow-hop', n: 'Crow-hop throws', pos: ['outfield'], who: 'solo', gear: 'Glove, balls, a net or a fence target',
    dose: '3 sets of 6', why: 'The crow hop turns your momentum into a stronger, more accurate throw.',
    steps: ['Field or catch the ball on your throwing-side foot.', 'Hop forward and land with your throwing-side foot turned sideways.',
      'Stride and throw on a line — aim for a one-hop to the target.'], cues: ['Catch on the throwing-side foot', 'Low, hard, one hop'],
    avoid: ['Throwing high rainbows', 'Hopping up instead of forward'], harder: 'Catch fly balls on the move before the crow hop.', fixes: [], yt: 'crow hop drill outfield throwing' },
  { id: 'find-wall', n: 'Find the wall', pos: ['outfield'], who: 'solo', gear: 'A fence or wall',
    dose: '8 reps', why: 'Knowing where the wall is lets you go all-out for a ball at the fence.',
    steps: ['Start 20 yards from the fence facing the infield.', 'Turn and sprint back, looking up as if tracking a ball.',
      'When you feel the warning track, reach your free hand back to find the fence and set up to jump.'], cues: ['Get to the wall first, then find the ball', 'Free hand finds the fence'],
    avoid: ['Running into the fence at full speed', 'Looking down at the wall'], harder: 'Add a partner throwing balls to the fence.', fixes: [], yt: 'outfield wall drill warning track' },
  { id: 'tennis-drop', n: 'Tennis ball drop (first step)', pos: ['outfield'], who: 'partner', gear: 'Tennis balls',
    dose: '10 reps', why: 'Trains reaction time and your first two steps.',
    steps: ['Partner stands 5–8 yards away holding a tennis ball in each hand, arms out.', 'They drop one without warning.',
      'Explode and catch it before the second bounce.'], cues: ['React, don\'t guess', 'Low and fast'], avoid: ['Leaning before the drop', 'Standing up on the first step'],
    harder: 'Move farther away.', fixes: [], yt: 'tennis ball drop reaction drill' },
  { id: 'fly-reads', n: 'Fly balls off the bat', pos: ['outfield'], who: 'partner', gear: 'A fungo bat (or throws), balls',
    dose: '15 fly balls', why: 'Reading the ball off the bat takes reps — throws aren\'t the same.',
    steps: ['Partner hits (or throws high) fly balls in different directions.', 'Take a good route with a drop step — never backpedal.',
      'Catch the ball above your throwing shoulder, moving toward your target.'], cues: ['First step back on anything you\'re not sure about', 'Catch it moving forward'],
    avoid: ['Drifting under the ball', 'Catching flat-footed'], harder: 'Add a throw to a base after every catch.', fixes: [], yt: 'outfield fly ball reading drill fungo' },
  { id: 'do-or-die', n: 'Do-or-die ground balls', pos: ['outfield'], who: 'partner', gear: 'Gloves, balls, a catcher or a net at home',
    dose: '10 reps', why: 'When the winning run is going home, you have to charge and throw on the run.',
    steps: ['Partner rolls a ball to you.', 'Charge hard and field it outside your glove-side foot.', 'Crow hop and throw on a line toward home.'],
    cues: ['Charge like an infielder', 'One motion from glove to throw'], avoid: ['Slowing down to field it', 'Missing the ball because you looked up early'],
    harder: 'Time the throw with a runner.', fixes: [], yt: 'do or die outfield drill' },
  { id: 'communication', n: 'Calling the ball', pos: ['outfield'], who: 'partner', gear: '2–3 fielders, balls',
    dose: '10–15 fly balls', why: 'Communication prevents collisions and dropped balls between fielders.',
    steps: ['Partner throws or hits balls between two outfielders.', 'The fielder who takes it calls "I got it!" three times, loud.',
      'The other fielder backs up. The center fielder has priority.'], cues: ['Call it loud and early', 'Back each other up'],
    avoid: ['Calling it late', 'Both players giving up on it'], harder: 'Add an infielder going out on shallow balls.', fixes: [], yt: 'outfield communication drill calling the ball' },

  /* ============================ THROWING (EVERYONE) ============================ */
  { id: 'one-knee', n: 'One-knee throws', pos: ['throwing'], who: 'solo', gear: 'A net or wall and balls (or a partner)',
    dose: '15 throws', why: 'Isolates the upper body so you learn a clean, efficient arm path.',
    steps: ['Kneel on your throwing-side knee with the glove-side knee up, pointing at the target.', 'Turn your shoulders, throw, and finish over the front knee.',
      'Keep your glove in front of your chest as you throw.'], cues: ['Throwing elbow at shoulder height', 'Chest finishes over the front knee'],
    avoid: ['Pushing the ball like a dart', 'Letting the glove fly open'], harder: 'Pick a small target on the net.', fixes: [], yt: 'one knee throwing drill baseball' },
  { id: 'quick-transfer', n: 'Quick transfer', pos: ['throwing'], who: 'solo', gear: 'Glove and a ball',
    dose: '3 sets of 15', why: 'A fast transfer from glove to hand saves time on every throw.',
    steps: ['Toss the ball into your glove.', 'Get it out and find a four-seam grip as fast as you can.',
      'Add a footwork step and a fake throw once the transfer is quick.'], cues: ['Glove to the middle of your chest', 'Feel for the seams'],
    avoid: ['Looking at the ball in your hand', 'Taking the glove to your ear'], harder: 'Do it without looking.', fixes: [], yt: 'quick transfer drill baseball four seam grip' },
  { id: 'catch-play', n: 'Catch-play progression', pos: ['throwing'], who: 'partner', gear: 'Gloves and a ball',
    dose: '10–12 minutes', why: 'Warm-up catch with a purpose builds accuracy and arm health.',
    steps: ['Wrist flicks at 15 feet, then one-knee throws.', 'Stand and throw with your feet set, then with a step.',
      'Back up in steps to 90–120 feet, throwing to your partner\'s chest every time.'], cues: ['Every throw to a target', 'Build up gradually'],
    avoid: ['Lazy throws', 'Throwing hard before you\'re warm'], harder: 'Keep score: chest = 2 points, glove side = 1.', fixes: [], yt: 'throwing progression warm up baseball' },
  { id: 'long-toss', n: 'Long toss', pos: ['throwing'], who: 'partner', gear: 'Gloves, a ball, open space',
    dose: '15–20 minutes, 1–2 times a week', why: 'Builds arm strength and a loose, healthy throwing motion.',
    steps: ['After catch play, back up gradually with an arc on the ball until you reach your max comfortable distance.',
      'Hold that distance for a few throws.', 'Come back in, throwing on a line harder as you get closer.'], cues: ['Loose and smooth going out', 'On a line coming in'],
    avoid: ['Jumping to max distance too fast', 'Doing it when your arm is sore'], harder: 'Add distance over weeks, not days. Log it in arm care.', fixes: [], yt: 'long toss program baseball' },

  /* ============================ BASE RUNNING ============================ */
  { id: 'lead-offs', n: 'Lead-offs and secondary leads', pos: ['running'], who: 'solo', gear: 'A base or a line',
    dose: '10 reps', why: 'A good lead and secondary lead get you to the next base faster.',
    steps: ['From first base, take a primary lead with 3–4 shuffle steps, weight balanced.', 'Practice getting back: step or dive back to the bag.',
      'On the pitch, take two quick shuffle steps (secondary lead) and read the ball.'], cues: ['Balanced, not leaning', 'Eyes on the pitcher'],
    avoid: ['Crossing your feet on the shuffle', 'Leaning so far you can\'t get back'], harder: 'Have a partner act as the pitcher with pickoffs.', fixes: [], yt: 'lead off base running drill' },
  { id: 'home-to-first', n: 'Home to first', pos: ['running'], who: 'solo', gear: 'A base (a stopwatch or partner to time it)',
    dose: '6 reps, full rest between', why: 'Beating out ground balls starts with the first step out of the box.',
    steps: ['Swing from your stance, then explode out of the box.', 'Run through the front edge of the bag — don\'t leap at it.',
      'Break down after the bag and look right for an overthrow.', 'Time it and log it in Baseball tests (home to first).'],
    cues: ['Run through the bag', 'Head down the line for the first steps'], avoid: ['Watching the ball out of the box', 'Diving into first'],
    harder: 'Race a partner fielding a ground ball.', fixes: [], yt: 'home to first base running drill' },
  { id: 'banana-turn', n: 'Rounding first (banana turn)', pos: ['running'], who: 'solo', gear: 'Bases',
    dose: '6 reps', why: 'A good turn at first can turn a single into a double.',
    steps: ['Curve out a few steps before the bag.', 'Hit the inside corner of the bag with either foot and lean in.',
      'Drive hard toward second.'], cues: ['Start the curve early', 'Lean in, stay fast'], avoid: ['A wide turn into right field', 'Slowing down to touch the bag'],
    harder: 'Do it from home to second and time it.', fixes: [], yt: 'rounding first base banana turn drill' },
  { id: 'steal-jumps', n: 'Steal jumps', pos: ['running'], who: 'partner', gear: 'A base, a partner acting as the pitcher',
    dose: '10 jumps', why: 'The steal is won in the first two steps.',
    steps: ['Partner acts as the pitcher and delivers to home or throws over.', 'On the first move to home, crossover and sprint 10 yards.',
      'On a pickoff move, get back.'], cues: ['Crossover, stay low', 'Know the pitcher\'s first move'], avoid: ['Standing up on the first step', 'Guessing early'],
    harder: 'Time it to second base.', fixes: [], yt: 'stealing second base jump drill' },
  { id: 'dirt-reads', n: 'Dirt-ball reads', pos: ['running'], who: 'partner', gear: 'A base, a ball; a partner acting as the catcher',
    dose: '10 reads', why: 'Advancing on balls in the dirt is free bases — if you read them early.',
    steps: ['Take your lead and your secondary lead as the "pitch" comes in.', 'Your partner either catches it clean or bounces it in the dirt.',
      'Read the downward angle early: go hard on the bounce, get back on a clean catch.'], cues: ['Read the angle, not the bounce', 'Be moving on your secondary lead'],
    avoid: ['Waiting to see where it bounces', 'Standing flat-footed at the end of your lead'], harder: 'Add a real throw from your partner to the next base.', fixes: [], yt: 'dirt ball read base running drill' },
  { id: 'sliding', n: 'Sliding practice', pos: ['running'], who: 'solo', gear: 'Wet grass or a slip mat, sliding shorts',
    dose: '8 slides', why: 'A good slide is safer and gets you to the base faster.',
    steps: ['Bent-leg slide: tuck one leg under the other like a figure 4 and sit down — don\'t jump.', 'Keep your hands up to protect your fingers.',
      'Practice a pop-up slide that gets you back on your feet.'], cues: ['Sit down, don\'t jump', 'Hands up'], avoid: ['Starting the slide too late', 'Sliding head-first without practice'],
    harder: 'Slide into a real base at game speed.', fixes: [], yt: 'how to slide baseball bent leg slide drill' }
];
const DRILL_BY_ID = Object.fromEntries(DRILLS.map(d => [d.id, d]));

/* Swing problems the Swing lab can find, and a simple thing to think about while you fix them.
   Drills above list the ones they help with in "fixes". */
const SWING_FAULTS = {
  head: { name: 'Head movement', what: 'Your head moves a lot between your stance and contact.',
    why: 'Your eyes move with your head, so the pitch looks faster and harder to track. Most good hitters keep their head within a few inches.', cue: 'Stride under a still head' },
  lunge: { name: 'Lunging / drifting forward', what: 'Your weight and head drift toward the pitcher before you swing.',
    why: 'You swing with your arms instead of your legs and hips, lose power, and get fooled by off-speed pitches.', cue: 'Land with your weight in the middle, then turn' },
  early_open: { name: 'Front shoulder opens early', what: 'Your shoulders start turning before (or right when) your front foot lands.',
    why: 'Opening early drags the barrel out of the zone — weak pulled grounders and swings and misses on outside pitches.', cue: 'Front shoulder stays closed until the foot lands' },
  no_sep: { name: 'Little hip-shoulder separation', what: 'Your hips and shoulders turn together, as one piece.',
    why: 'The stretch between hips and shoulders (separation) is one of the biggest sources of bat speed.', cue: 'Hips go, shoulders wait' },
  sequence: { name: 'Swing sequence out of order', what: 'Your shoulders or arms speed up before your hips do.',
    why: 'Power is built from the ground up — hips, then shoulders, then arms, then bat. Out of order means lost bat speed.', cue: 'Start the swing with your back hip' },
  cast: { name: 'Casting (hands away from the body)', what: 'Your hands push away from your body early in the swing, like casting a fishing line.',
    why: 'A wide, long swing is slower to the ball and can\'t handle inside pitches.', cue: 'Knob to the ball, elbow to your side' },
  extension: { name: 'Short extension', what: 'Your arms don\'t fully extend through and after contact.',
    why: 'Full extension keeps the barrel in the hitting zone longer and adds carry to the ball.', cue: 'Throw your hands at the pitcher after contact' },
  block: { name: 'Soft front side', what: 'Your front knee keeps bending instead of firming up as you swing.',
    why: 'A firm front leg stops your forward move and turns it into rotation. A soft one leaks power forward.', cue: 'Stride, then post up on the front leg' },
  collapse: { name: 'Back side collapses', what: 'Your hips and back shoulder drop down as you swing.',
    why: 'Dropping under the ball causes pop-ups and swings under high fastballs.', cue: 'Stay tall through the ball' },
  stride_open: { name: 'Stride is open ("in the bucket")', what: 'Your front foot steps away from the plate.',
    why: 'Stepping out pulls your whole body off the ball, so outside pitches become hard to reach.', cue: 'Stride straight at the pitcher' },
  stride_closed: { name: 'Stride is too closed', what: 'Your front foot steps across toward the plate.',
    why: 'A crossed-over stride blocks your hips from turning, so inside pitches jam you.', cue: 'Stride straight at the pitcher' },
  overstride: { name: 'Stride is too long', what: 'Your feet end up very far apart when your front foot lands.',
    why: 'An overstride drops your head and eyes and makes it hard to rotate.', cue: 'Short, soft stride' },
  posture: { name: 'Posture changes', what: 'Your upper body stands up or tips over during the swing.',
    why: 'Changing your spine angle moves your eyes and the barrel\'s path — mis-hits and pop-ups.', cue: 'Keep your spine angle until after contact' },
  balance: { name: 'Off-balance finish', what: 'You fall off toward the plate or away from it after the swing.',
    why: 'Losing balance at the end means something earlier in the swing was out of control.', cue: 'Hold your finish for 3 seconds' },
  slow: { name: 'Slow swing timing', what: 'It takes a long time from starting your swing to contact.',
    why: 'The faster you get to the ball, the longer you can wait on the pitch before deciding to swing.', cue: 'Short to the ball, long through it' },
  load: { name: 'Little or no load', what: 'Your hands and shoulders barely move back before the swing.',
    why: 'A small load gets your body coiled and on time — without it you have to generate everything from a standstill.', cue: 'Hands back as the front foot goes forward' },
  stance: { name: 'Stance needs work', what: 'Your stance is very narrow, very wide or stiff-legged.',
    why: 'An athletic stance (knees bent, feet a bit wider than shoulders) lets you move and adjust.', cue: 'Athletic stance — knees soft, weight on the balls of your feet' }
};
